{"name": "test_x[4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 3\n +  where 3 = <bound method Random.randint of <random.Random object at 0x00000228284070A0>>(1, 3)\n +    where <bound method Random.randint of <random.Random object at 0x00000228284070A0>> = random.randint", "trace": "x = 4\n\n    @pytest.mark.parametrize('x', data)\n    def test_x(x):\n>       assert x == random.randint(1,3)\nE       assert 4 == 3\nE        +  where 3 = <bound method Random.randint of <random.Random object at 0x00000228284070A0>>(1, 3)\nE        +    where <bound method Random.randint of <random.Random object at 0x00000228284070A0>> = random.randint\n\ntest_pytest2.py:22: AssertionError"}, "parameters": [{"name": "x", "value": "4"}], "start": 1597154468266, "stop": 1597154468267, "uuid": "165a9926-0252-4104-873a-ee063b9bc98d", "historyId": "3389a17dfd755f8fc7232706f4cdfae9", "testCaseId": "b1db76a50f52df3788772fa82f169c41", "fullName": "test_pytest2#test_x", "labels": [{"name": "suite", "value": "test_pytest2"}, {"name": "host", "value": "lihaoil"}, {"name": "thread", "value": "8568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest2"}]}