{"name": "test_add2", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntest_pytest1.py:31: AssumptionFailure\n>>\tpytest.assume(2 + 5 == 1)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               test_pytest1.py:31: AssumptionFailure\nE               >>\tpytest.assume(2 + 5 == 1)\nE               AssertionError: assert False\n\nd:\\python\\lib\\site-packages\\six.py:702: FailedAssumption"}, "attachments": [{"name": "stdout", "source": "0744aaa1-01d5-458e-9aa9-59fddcffa952-attachment.txt", "type": "text/plain"}], "start": 1597154467548, "stop": 1597154467884, "uuid": "23248f37-ebf5-45a1-948b-d01fb9173a13", "historyId": "c0a2b91384bbf67a8e9238ca7d63d92e", "testCaseId": "38b0c869c8b5daf09ff06fb6f89b1d22", "fullName": "test_pytest1#test_add2", "labels": [{"name": "suite", "value": "test_pytest1"}, {"name": "host", "value": "lihaoil"}, {"name": "thread", "value": "8568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest1"}]}